version: '3'

services:
  app:
    build: ./app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - task_loader
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=myapp.settings
      - DATABASE_URL=postgres://postgres:password@db:5432/barber
      - REDIS_URL=redis://redis:6379/0
      - TASK_LOADER_URL=http://task_loader:8001
      - DJANGO_SUPERUSER_USERNAME=admin
    command: >
      bash -c "
        python manage.py makemigrations && 
        python manage.py makemigrations users &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./app:/app

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: barber
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  redis:
    image: redis:latest
    restart: always

  task_loader:
    build: ./task_loader
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/barber
      - REDIS_URL=redis://redis:6379/0
    command: python task_loader.py
    volumes:
      - ./task_loader:/app

  chatbot:
    build: ./chatbot
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/barber
      - REDIS_URL=redis://redis:6379/0
    command: python chatbot.py
    volumes:
      - ./chatbot:/app